### ISSUE TITLE
Diseño de Test Usuarios caja negra

### ISSUE THREAD

**Issue by Lizerat** [UNIZAR-30226-2024-08/back-end#23]

**Comment by LuciaMoralesRosa** [comment]
Casos de prueba para la funcion "CrearUsuario". Se encuentra en la carpeta "Dir_Backend/Test-Particiones de equivalencia"

![image](https://github.com/UNIZAR-30226-2024-08/back-end/assets/55547174/a117df02-e0d4-4778-b609-4bad866d720e)
@Lizerat

**Comment by LuciaMoralesRosa** [comment]
Casos de prueba para la funcion "ActualizarUsuario". Se encuentra en la carpeta "Dir_Backend/Test-Particiones de equivalencia"
**Tener en cuenta: ** no es igual que los casos de prueba anteriores. Cambian los atributos _gmail y nombre_

![image](https://github.com/UNIZAR-30226-2024-08/back-end/assets/55547174/9afd3680-43fc-4705-9cb1-30d0d637b445)
@Lizerat

**Comment by LuciaMoralesRosa** [comment]
Casos de prueba para la funcion "BorrarUsuario". Se encuentra en la carpeta "Dir_Backend/Test-Particiones de equivalencia"

![image](https://github.com/UNIZAR-30226-2024-08/back-end/assets/55547174/1617500e-4ae8-45fd-8844-59eb36c150ff)
@Lizerat

**Comment by LuciaMoralesRosa** [comment]
Casos de prueba para la funcion "BorrarUsuario". Se encuentra en la carpeta "Dir_Backend/Test-Particiones de equivalencia"

![image](https://github.com/UNIZAR-30226-2024-08/back-end/assets/55547174/3cd8ab90-8807-48f9-baa9-e186c8382856)
@Lizerat

**Comment by LuciaMoralesRosa** [comment]
No hay más métodos sobre los que diseñar tests en UsuarioDAO.
