### ISSUE TITLE
Diseñar Casos de Prueba GestorUsuarios

### ISSUE THREAD

**Issue by Lizerat** [UNIZAR-30226-2024-08/back-end#24]

**Comment by LuciaMoralesRosa** [comment]
Casos de prueba para la funcion "IniciarSesion". Se encuentra en la carpeta "Dir_Backend/Test-Particiones de equivalencia"

![image](https://github.com/UNIZAR-30226-2024-08/back-end/assets/55547174/b6620e7d-4cd8-4066-ace2-5968e85a5461)
@Lizerat

**Comment by LuciaMoralesRosa** [comment]
Casos de prueba para la funcion "CerrarSesion". Se encuentra en la carpeta "Dir_Backend/Test-Particiones de equivalencia"

![image](https://github.com/UNIZAR-30226-2024-08/back-end/assets/55547174/3360c7cc-b46c-4051-84bf-c8fd61a15d0d)

**Comment by LuciaMoralesRosa** [comment]
Casos de prueba para la funcion "cambiarNombre". Se encuentra en la carpeta "Dir_Backend/Test-Particiones de equivalencia"

![image](https://github.com/UNIZAR-30226-2024-08/back-end/assets/55547174/97e91ff3-e48d-43d8-93ff-b288ca2b6dff)
@Lizerat

**Comment by LuciaMoralesRosa** [comment]
Casos de prueba para la funcion "cambiarCartas". Se encuentra en la carpeta "Dir_Backend/Test-Particiones de equivalencia"

![image](https://github.com/UNIZAR-30226-2024-08/back-end/assets/55547174/59373eda-6823-4ab9-8ecb-12546af239b8)
@Lizerat

**Comment by LuciaMoralesRosa** [comment]
Casos de prueba para la funcion "cambiarAvatar". Se encuentra en la carpeta "Dir_Backend/Test-Particiones de equivalencia"

![image](https://github.com/UNIZAR-30226-2024-08/back-end/assets/55547174/59373eda-6823-4ab9-8ecb-12546af239b8)
@Lizerat

**Comment by LuciaMoralesRosa** [comment]
Casos de prueba para la funcion "actualizarUsuario". Se encuentra en la carpeta "Dir_Backend/Test-Particiones de equivalencia"

![image](https://github.com/UNIZAR-30226-2024-08/back-end/assets/55547174/5d2c73ee-64e1-4a62-a005-760b3acdf19c)
@Lizerat

**Comment by LuciaMoralesRosa** [comment]
Se han completado todos los tests para los metodos de la clase
