### ISSUE TITLE
Desarrollar vista de módulos (VO,DAO,Gestor)

### ISSUE THREAD

**Issue by carlotamgm** [UNIZAR-30226-2024-08/back-end#6]

**Comment by Lizerat** [comment]
He revisado todo @carlotamgm he corregido un par de fallos, pero en principio muy buen trabajo con los DAO's/VO's. He añadido además los modulos "internos" en rojo (Los que vamos a usar nosotros pero no son ni DAO's ni VO's (Base de Datos) ni servicios de la API). Sin embargo solo he puesto los titulos y las relaciones que se me han ocurrido a priori, habría que ponerse a diseñarlas por dentro (atributos, metodos, etc...) y ver si necesitamos más clases.

**Comment by Lizerat** [comment]
Terminada la parte para usuarios

**Comment by carlotamgm** [comment]
Finalizada la vista de módulos tras varias revisiones.
