### ISSUE TITLE
Implementar Usuarios

### ISSUE THREAD

**Issue by Lizerat** [UNIZAR-30226-2024-08/back-end#7]
Implementar Gestor de Usuarios para Registro y autenticación.

**Comment by carlotamgm** [comment]
Tras implementar el registro de usuarios con la API de Google, se ha terminado la parte de autenticación de usuarios en backend. Se realizaron modificaciones en las funciones de los archivos GestorUsuarios.ts, UsuarioVO.ts y UsuarioDAO.ts, y se han expuesto algunas de estas funciones al frontend a través de la API.
